logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
